repos:

  - repo: https://github.com/compilerla/conventional-pre-commit.git
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [
            feat,
            feat!,
            fix,
            build,
            chore,
            ci,
            docs,
            perf,
            refactor,
            revert,
            wip,
            style,
          ] # optional: list of Conventional Commits types to allow
